### ISSUE TITLE
Whats the reason for writing a new package?

### ISSUE THREAD

**Issue by gajus** [sindresorhus/require-uncached#4]
I am already maintaining https://github.com/gajus/require-new.

In the spirit of preventing code/ effort duplication, is there any reason to write another implementation instead of contributing to the existing one?

I am happy to work out any feature deficiencies.

**Comment by gajus** [comment]
Just had a look at the commit history. Turns out that I am the bad guy:

|package|date of the first commit|
|---|---|
|require-uncached|19 Jul 2014|
|require-new|15 Nov 2014|

**Comment by gajus** [comment]
I am quite happy to deprecate my package in favour of yours: the two seem to be functionally equivalent. @sindresorhus thoughts?

**Comment by sindresorhus** [comment]
Up to you, but probably the best, otherwise you'll need to handle https://github.com/sindresorhus/require-uncached/commit/b9780927e53ec0190d64050389a158f9a451299f too.

**Comment by gajus** [comment]
Done.

https://github.com/gajus/require-new#deprecated
